
title: تجربه باز
description: در ستایش تجربه کردن و یادگرفتن همیشگی / open experience
author: کیاوش
language: Farsi

url: http://kiavash.one/
root: /

icon: /static/img/logo.png
css: miramal.css

static: /static/
imageurl: /img/

default_extension: md

permalink: :year/:month/:day/:title/

default_markup: markmod

post_num: all
archive_post_num: all
feed_output: atom.xml

template: miramal

disqus_shortname: kiavash

lists:
 - tags
 - categories

namespace: 
  آموزش: education
  سرور: server
  درباره: about
  شخصی: personal
  میرا: mira
  اوبونتو: ubuntu
  امنیت: security
  

plugins:
 - Jdate
